# -*- coding: utf-8 -*-
"""Untitled144.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jd722ADUcKlUA_9R8iWjKQSD6IxtLF7U
"""

import shutil

best_pt_path = "/content/drive/MyDrive/YOLO_Project/stage1/runs/train_20260614_081102/weights/best.pt"
save_dir = "/content/drive/MyDrive/YOLO_Project/stage1/model"
os.makedirs(save_dir, exist_ok=True)

shutil.copy(best_pt_path, os.path.join(save_dir, "best_model.pt"))
print(" Model saved as .pt file")

from ultralytics import YOLO
model = YOLO("/content/drive/MyDrive/YOLO_Project/stage1/model/best_model.pt")

""" Install & Import"""

!pip install faiss-gpu transformers Pillow -q

import os, torch, faiss, json
import numpy as np
from PIL import Image
from pathlib import Path
from ultralytics import YOLO
from transformers import CLIPProcessor, CLIPModel
from tqdm import tqdm

DRIVE_BASE = "/content/drive/MyDrive/YOLO_Project"
YOLO_MODEL_PATH = f"{DRIVE_BASE}/stage1/model/best_model.pt"
DATASET_PATH = "/content/deepfashion2/train/images"
INDEX_SAVE_DIR = f"{DRIVE_BASE}/faiss_index"
os.makedirs(INDEX_SAVE_DIR, exist_ok=True)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {DEVICE}")

"""Build FAISS index"""

import os, torch, faiss, json
import numpy as np
from PIL import Image
from pathlib import Path
from ultralytics import YOLO
from transformers import CLIPProcessor, CLIPModel
from tqdm import tqdm

DRIVE_BASE = "/content/drive/MyDrive/YOLO_Project"
YOLO_MODEL_PATH = f"{DRIVE_BASE}/stage1/model/best_model.pt"
DATASET_PATH = "/content/deepfashion2/train/images"
INDEX_SAVE_DIR = f"{DRIVE_BASE}/faiss_index"
CHECKPOINT_DIR = f"{DRIVE_BASE}/faiss_index/checkpoints"
os.makedirs(INDEX_SAVE_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
CHECKPOINT_EVERY = 500

CLASS_NAMES = [
    "dress","long_sleeved_dress","long_sleeved_outwear",
    "long_sleeved_shirt","short_sleeved_outwear","short_sleeved_shirt",
    "shorts","skirt","trousers","vest","vest_dress"
]

yolo = YOLO(YOLO_MODEL_PATH)
clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").to(DEVICE)
clip_proc  = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

def get_clip_embedding(crop_img):
    inputs = clip_proc(images=crop_img, return_tensors="pt").to(DEVICE)
    with torch.no_grad():
        outputs = clip_model.vision_model(**inputs)
        emb = clip_model.visual_projection(outputs.pooler_output)
    emb = emb / emb.norm(dim=-1, keepdim=True)
    return emb.cpu().numpy().astype("float32")

# --- Progress faylını oxu (varsa) ---
progress_file = f"{CHECKPOINT_DIR}/progress.json"
if os.path.exists(progress_file):
    with open(progress_file) as f:
        progress = json.load(f)
    start_idx = progress["last_completed_idx"] + 1
    print(f"  Checkpoint tapıldı! {start_idx}-continue from ...")
else:
    start_idx = 0
    print("starting ...")


all_embeddings = {i: [] for i in range(len(CLASS_NAMES))}
all_metadata   = {i: [] for i in range(len(CLASS_NAMES))}

for cls_id, cls_name in enumerate(CLASS_NAMES):
    emb_path  = f"{CHECKPOINT_DIR}/{cls_name}_embs.npy"
    meta_path = f"{CHECKPOINT_DIR}/{cls_name}_meta.json"
    if os.path.exists(emb_path):
        arr = np.load(emb_path)
        all_embeddings[cls_id] = list(arr)
        with open(meta_path) as f:
            all_metadata[cls_id] = json.load(f)
        print(f"   {cls_name}: {len(arr)} embedding dowloaded")


image_paths = sorted(list(Path(DATASET_PATH).glob("*.jpg")))
print(f"\nTotal: {len(image_paths)} şəkil, {start_idx} from starting \n")

for i, img_path in enumerate(tqdm(image_paths[start_idx:], initial=start_idx, total=len(image_paths))):
    global_idx = start_idx + i

    try:
        results = yolo(str(img_path), verbose=False, conf=0.3)[0]
        if results.boxes is None or len(results.boxes) == 0:
            continue

        img = Image.open(img_path).convert("RGB")
        for box in results.boxes:
            cls_id = int(box.cls[0])
            x1,y1,x2,y2 = map(int, box.xyxy[0].tolist())
            crop = img.crop((x1,y1,x2,y2))
            if crop.width < 20 or crop.height < 20:
                continue
            emb = get_clip_embedding(crop)
            all_embeddings[cls_id].append(emb)
            all_metadata[cls_id].append({
                "image_path": str(img_path),
                "bbox": [x1,y1,x2,y2],
                "class": CLASS_NAMES[cls_id]
            })
    except Exception as e:
        print(f"error {img_path.name}: {e}")
        continue

    # --- Checkpoint ---
    if (global_idx + 1) % CHECKPOINT_EVERY == 0:
        for cls_id, cls_name in enumerate(CLASS_NAMES):
            if all_embeddings[cls_id]:
                np.save(f"{CHECKPOINT_DIR}/{cls_name}_embs.npy",
                        np.vstack(all_embeddings[cls_id]))
                with open(f"{CHECKPOINT_DIR}/{cls_name}_meta.json","w") as f:
                    json.dump(all_metadata[cls_id], f)
        with open(progress_file, "w") as f:
            json.dump({"last_completed_idx": global_idx}, f)
        print(f"\n Checkpoint: {global_idx+1}/{len(image_paths)} saved")


print("\nloading...")
for cls_id, embs in all_embeddings.items():
    if not embs:
        print(f"  Skip {CLASS_NAMES[cls_id]}")
        continue
    matrix = np.vstack(embs)
    index = faiss.IndexFlatIP(512)
    index.add(matrix)
    cls_name = CLASS_NAMES[cls_id]
    faiss.write_index(index, f"{INDEX_SAVE_DIR}/{cls_name}.index")
    with open(f"{INDEX_SAVE_DIR}/{cls_name}_meta.json","w") as f:
        json.dump(all_metadata[cls_id], f)
    print(f"   {cls_name}: {len(embs)} item")

print("\n Complted!")